#!/usr/bin/env zsh
cleanupEnv() {
    pushd $DOTFILES
    for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
    do
        echo "Removing $folder"
        stow -D $folder
    done
    popd
}

setupEnv() {
    pushd $DOTFILES
    for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
    do
        stow -D $folder
        stow $folder
    done
    popd
}

if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="awesome,bat,bash,bin,dolphin,face,lazygit,newsboat,personal,python,qimgv,lf,micro,screenkey,shortcuts,tmux,zsh"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi


# to dry run
# stow -n -vv -d others/theprimeagen-dotfiles/bin/.local/bin/ -t bin/.local/bin/ .

# stow -d others/theprimeagen-dotfiles/bin/.local/bin/ -t bin/.local/bin/ .

# delete stowed files
# stow -D -vv -d others/theprimeagen-dotfiles/bin/.local/bin/ -t bin/.local/bin/ .
